name: Industrial Ingestion Pipeline

on:
  schedule:
    - cron: '0 * * * *' # Executa a cada hora
  workflow_dispatch:     # Permite disparo manual direto no GitHub

jobs:
  run-ingestion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run IoT Telemetry Generator
        env:
          CONFLUENT_BOOTSTRAP_SERVERS: pkc-619z3.us-east1.gcp.confluent.cloud:9092
          CONFLUENT_API_KEY: Z2PLHOH5YAYJTAJW
          CONFLUENT_API_SECRET: cfltb2UKU9D0ecubNleSuolNbhde4ZHovCI1obdEIC4bR/JNQ6f6WtmvxKhWb04A
        run: python src/generators/iot_telemetry_generator.py

      - name: Run Weather API Ingestion
        env:
          CONFLUENT_BOOTSTRAP_SERVERS: pkc-619z3.us-east1.gcp.confluent.cloud:9092
          CONFLUENT_API_KEY: Z2PLHOH5YAYJTAJW
          CONFLUENT_API_SECRET: cfltb2UKU9D0ecubNleSuolNbhde4ZHovCI1obdEIC4bR/JNQ6f6WtmvxKhWb04A
        run: python src/api/weather_api_ingestion.py
      - name: Send Telegram Notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🚀 *Industrial Ingestion Pipeline*

            *Status:* ${{ job.status == 'success' && '✅ Sucesso' || '❌ Falha' }}
            *Run ID:* #${{ github.run_number }}
            *Repositório:* ${{ github.repository }}
            *Mensagem:* Lote de telemetria processado e enviado ao Confluent Cloud!
